version: "2.15.1"
services:
   db:
    image: postgres_auth
    container_name: postgres_auth
    build: ./db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - db-pgdata:/var/lib/postgresql/data   
      - db-extra-data:/data
volumes:
  db-pgdata:
    driver: local
  db-extra-data:
    driver: local  
