version: "2.15.1"
services:
   db:
    image: postgres:latest
    container_name: postgres_auth
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - db-pgdata:/var/lib/postgresql/data   
      - ./db/00_db_create_auth_schema.sh:/docker-entrypoint-initdb.d/00_db_create_auth_schema.sh
      - ./db/10_db_create_test-roles.sh:/docker-entrypoint-initdb.d/10_db_create_test-roles.sh
      - ./db/20_replace_pg_hba.conf.sh:/docker-entrypoint-initdb.d/20_replace_pg_hba.conf.sh
volumes:
  db-pgdata:
    driver: local
 
